/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as AdminAboutRouteImport } from './routes/admin.about'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/admin/about',
  path: '/admin/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/admin/hero',
  path: '/admin/hero',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/admin/programs',
  path: '/admin/programs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programs': typeof AdminProgramsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programs': typeof AdminProgramsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activities': typeof ActivitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/programs': typeof AdminProgramsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activities'
    | '/contact'
    | '/gallery'
    | '/programs'
    | '/admin/about'
    | '/admin/dashboard'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/programs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activities'
    | '/contact'
    | '/gallery'
    | '/programs'
    | '/admin/about'
    | '/admin/dashboard'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activities'
    | '/contact'
    | '/gallery'
    | '/programs'
    | '/admin/about'
    | '/admin/dashboard'
    | '/admin/hero'
    | '/admin/login'
    | '/admin/programs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitiesRoute: typeof ActivitiesRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ProgramsRoute: typeof ProgramsRoute
  AdminAboutRoute: typeof AdminAboutRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/admin/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/admin/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/admin/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitiesRoute: ActivitiesRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ProgramsRoute: ProgramsRoute,
  AdminAboutRoute: AdminAboutRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProgramsRoute: AdminProgramsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
